[build]
  publish = 'dist/'
  command = 'yarn build'

[[redirects]]
  from = '/*'
  to = '/'
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-a11y"